language: python
python:
- '3.8'
- '3.7'
- '3.6'
branches:
  only:
    - master
install:
- pip install -e .
- pip install -r requirements.txt
script:
- pytest --cov=./
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: ~
  on:
    tags: true

